defaults:
  - base.yaml
  - _self_

tracker:
  _target_: boxmot.BoTSORT
  model_weights: null
  fp16: false
  device: cpu
  with_reid: false
name: bot_sort-${.detection.cfg.name}  # mot task depends on detection task
