project_root: /path/to/project
python: /path/to/python
name: default-${.detection.cfg.name}  # mot task depends on detection task
recording_dir: ./data/recording
prediction_dir: ./result/mot/${.name}
detection: ${detection}
