_target_: tasks.detection.detic.DeticObjectDetection
cfg:
  project_root: /path/to/project
  python: /path/to/python
  name: detic
  recording_dir: ./data/recording
  prediction_dir: ./result/detection/${.name}

  exp_name: Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size
  config: ${.project_root}/configs/${.exp_name}.yaml
  model: ${.project_root}/models/${.exp_name}.pth
  confidence_threshold: 0.5
