python: /path/to/python
project_dir: /path/to/project
config: /path/to/config/file
model: /path/to/model/checkpoint
recording_dir: /path/to/recording/directory
prediction_dir: ./result/detic
dump_dir: /path/to/detic/dump/directory
