defaults:
  - _self_

project: multimodal-reference

work_dir: ${hydra:runtime.cwd}

# name of the run is accessed by loggers
# should be used along with experiment mode
name: default

exp_dir: ${work_dir}/result/mmref/${name}
config_name: ${hydra:job.config_name}

luigi:
  local_scheduler: true
  workers: 4
  log_level: WARNING

hydra:
  output_subdir: null
  # hydra_logging: null
  # job_logging: null
  run:
    dir: ${exp_dir}
  sweep:
    dir: ${work_dir}/multirun_result
    subdir: ${name}-${hydra:job.num}
  job:
    config:
      override_dirname:
        kv_sep: '_'
        item_sep: '-'
