defaults:
  - base.yaml
  - cohesion: example.yaml
  - detic_detection: default.yaml
  - mdetr: example.yaml
  - glip: example.yaml
  - detic: default.yaml
  - mot: example.yaml
  - _self_

scenario_ids: []
id_file: null

dataset_dir: /path/to/dataset
gold_knp_dir: /path/to/gold/knp/file
gold_annotation_dir: /path/to/gold/annotation

phrase_grounding_model: glip  # mdetr, glip, detic
coref_relax_mode: null  # null, pred, gold
mot_relax_mode: null  # null, pred, gold

names:
  mdetr: mdetr_${mdetr.name}
  glip: glip_${glip.name}
  detic: detic_${detic.name}

coref_relax_names:
  pred: -coref_relax_pred
  gold: -coref_relax_gold

mot_relax_names:
  pred: -mot_relax_${mot.name}
  gold: -mot_relax_gold

name: ${names[${phrase_grounding_model}]}${get:${coref_relax_names},${coref_relax_mode},""}${get:${mot_relax_names},${mot_relax_mode},""}
