defaults:
  - base.yaml
  - cohesion: example.yaml
  - mdetr: example.yaml
  - glip: example.yaml
  - mot: example.yaml
  - _self_

dataset_dir: /path/to/dataset
gold_knp_dir: /path/to/gold/knp/file
gold_annotation_dir: /path/to/gold/annotation

phrase_grounding_model: glip  # mdetr, glip
coref_relax_mode: null  # null, pred, gold
mot_relax_mode: null  # null, pred, gold
