defaults:
  - base.yaml
  - cohesion: example.yaml
  - mdetr: example.yaml
  - glip: example.yaml
  - detic: default.yaml
  - mot: example.yaml
  - _self_

scenario_ids: []
id_file: null

dataset_dir: /path/to/dataset
gold_knp_dir: /path/to/gold/knp/file
gold_annotation_dir: /path/to/gold/annotation

phrase_grounding_model: glip  # mdetr, glip, detic
coref_relax_mode: null  # null, pred, gold
mot_relax_mode: null  # null, pred, gold
