defaults:
  - base.yaml
  - cohesion: example.yaml
  - detection: detic.yaml
  - mdetr: example.yaml
  - glip: example.yaml
  - detic: default.yaml
  - mot: example.yaml
  - _self_

scenario_ids: []
id_file: null

result_dir: ./result
dataset_dir: ./data/dataset
gold_knp_dir: ./data/knp
gold_annotation_dir: ./data/image_text_annotation

phrase_grounding_model: glip  # mdetr, glip, detic
coref_relax_mode: null  # null, pred, gold
mot_relax_mode: null  # null, pred, gold
confidence_modification_method: max  # max, mean, min

names:
  mdetr: mdetr_${mdetr.name}
  glip: glip_${glip.name}
  detic: detic_${detic.name}

coref_relax_names:
  pred: -coref_relax_pred
  gold: -coref_relax_gold

mot_relax_names:
  pred: -mot_relax_${mot.name}-${confidence_modification_method}
  gold: -mot_relax_gold-${confidence_modification_method}

name: ${names[${phrase_grounding_model}]}${get:${coref_relax_names},${coref_relax_mode},""}${get:${mot_relax_names},${mot_relax_mode},""}
