defaults:
  - base.yaml
  - _self_

cohesion:
  python: /path/to/cohesion/.venv/bin/python
  project_root: /path/to/cohesion
  checkpoint: /path/to/trained/cohesion/checkpoint

mdetr:
  python: /path/to/mdetr/.venv/bin/python
  project_root: /path/to/mdetr
  checkpoint: /path/to/trained/mdetr/checkpoint
  backbone_name: timm_tf_efficientnet_b3_ns
  text_encoder: xlm-roberta-base
  batch_size: 16

dataset_dir: /path/to/dataset
gold_knp_file: /path/to/gold/knp/file
prediction_dir: /path/to/prediction

coref_relaxed_prediction: false
